USE [ProductChase]
GO

/****** Object:  Trigger [dbo].[COST_CALCULATION_NEW]    Script Date: 07/05/2023 00:14:28 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[COST_CALCULATION_NEW]
ON [dbo].[TBLMOVEMENT]
AFTER INSERT
AS

DECLARE @PRODUCTID INT
SELECT @PRODUCTID=PRODUCT FROM INSERTED

DECLARE @MOVID INT
SELECT @MOVID = CLIENT FROM INSERTED

DECLARE @COST DECIMAL(18,2)
SELECT COST=@COST FROM TBLMOVEMENT INNER JOIN TBLPRODUCTS ON TBLMOVEMENT.PRODUCT=TBLPRODUCTS.PRODUCTID WHERE PRODUCTID=@PRODUCTID

UPDATE TBLMOVEMENT
SET COST = @COST * QUANTITY
WHERE MOVEMENTID = @MOVID
GO

ALTER TABLE [dbo].[TBLMOVEMENT] ENABLE TRIGGER [COST_CALCULATION_NEW]
GO


