USE [ProductChase]
GO

/****** Object:  Trigger [dbo].[DATEAPPLY]    Script Date: 07/05/2023 00:15:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[DATEAPPLY]
ON [dbo].[TBLMOVEMENT]
AFTER INSERT
AS
BEGIN
	UPDATE TBLMOVEMENT
	SET SELLDATE = GETDATE()
	FROM INSERTED
	WHERE TBLMOVEMENT.MOVEMENTID = INSERTED.MOVEMENTID;
	
END;
GO

ALTER TABLE [dbo].[TBLMOVEMENT] ENABLE TRIGGER [DATEAPPLY]
GO


