USE [ProductChase]
GO

/****** Object:  Trigger [dbo].[STOCK_FLOW_UPDATE]    Script Date: 07/05/2023 00:15:51 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[STOCK_FLOW_UPDATE]
ON [dbo].[TBLMOVEMENT]
AFTER INSERT, UPDATE, DELETE
AS
BEGIN
    -- Insert işlemi sonrası stok güncelleme
    --IF EXISTS (SELECT 1 FROM inserted)
    --BEGIN
    --    UPDATE TBLPRODUCTS
    --    SET PRODUCTSTOCK = PRODUCTSTOCK - INSERTED.QUANTITY FROM INSERTED
    --    WHERE PRODUCTID IN (SELECT PRODUCT FROM inserted);
    --END;
    -- Delete işlemi sonrası stok güncelleme
    --IF EXISTS (SELECT 1 FROM deleted)
    --BEGIN
    --    UPDATE TBLPRODUCTS
    --    SET PRODUCTSTOCK = PRODUCTSTOCK + DELETED.QUANTITY FROM DELETED
    --    WHERE PRODUCTID IN (SELECT PRODUCT FROM deleted);
    --END;
    -- Update işlemi sonrası stok güncelleme
    IF EXISTS (SELECT 1 FROM inserted) AND EXISTS (SELECT 1 FROM deleted)
    BEGIN

		DECLARE @OLD_PRODUCTID INT
		SELECT @OLD_PRODUCTID = DELETED.PRODUCT FROM DELETED

		DECLARE @NEW_PRODUCTID INT
		SELECT @NEW_PRODUCTID = INSERTED.PRODUCT FROM INSERTED

		DECLARE @NEW_QUANTITY INT
		SELECT @NEW_QUANTITY = INSERTED.QUANTITY FROM INSERTED

		DECLARE @OLD_QUANTITY INT
		SELECT @OLD_QUANTITY = DELETED.QUANTITY FROM DELETED

		
        UPDATE TBLPRODUCTS
			SET PRODUCTSTOCK = PRODUCTSTOCK + @OLD_QUANTITY
			WHERE PRODUCTID = @OLD_PRODUCTID
		UPDATE TBLPRODUCTS
			SET PRODUCTSTOCK = PRODUCTSTOCK - @NEW_QUANTITY
			WHERE PRODUCTID = @NEW_PRODUCTID
			
        --SET PRODUCTSTOCK = PRODUCTSTOCK + (SELECT SUM(QUANTITY) FROM deleted WHERE TBLPRODUCTS.PRODUCTID = deleted.PRODUCT)
        --                    - (SELECT SUM(QUANTITY) FROM inserted WHERE TBLPRODUCTS.PRODUCTID = inserted.PRODUCT)
        --WHERE PRODUCTID IN (SELECT PRODUCT FROM deleted UNION SELECT PRODUCT FROM inserted);
    END;
END;
GO

ALTER TABLE [dbo].[TBLMOVEMENT] ENABLE TRIGGER [STOCK_FLOW_UPDATE]
GO


