USE [ProductChase]
GO

/****** Object:  Trigger [dbo].[STOCKFLOW]    Script Date: 07/05/2023 00:16:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[STOCKFLOW]
ON [dbo].[TBLMOVEMENT]
AFTER INSERT
AS
BEGIN
    UPDATE TBLPRODUCTS
    SET PRODUCTSTOCK = PRODUCTSTOCK - INSERTED.QUANTITY
    FROM INSERTED
    WHERE TBLPRODUCTS.PRODUCTID = INSERTED.PRODUCT;
END;
GO

ALTER TABLE [dbo].[TBLMOVEMENT] ENABLE TRIGGER [STOCKFLOW]
GO


