USE [ProductChase]
GO

/****** Object:  Trigger [dbo].[STOCKFLOWBACK]    Script Date: 07/05/2023 00:16:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[STOCKFLOWBACK]
ON [dbo].[TBLMOVEMENT]
AFTER DELETE
AS
BEGIN
    UPDATE TBLPRODUCTS
    SET PRODUCTSTOCK = PRODUCTSTOCK + DELETED.QUANTITY
    FROM DELETED
    WHERE TBLPRODUCTS.PRODUCTID = DELETED.PRODUCT;
END;
GO

ALTER TABLE [dbo].[TBLMOVEMENT] ENABLE TRIGGER [STOCKFLOWBACK]
GO


