USE [ProductChase]
GO

/****** Object:  Trigger [dbo].[COSTCALCULATIONUPDATE]    Script Date: 07/05/2023 00:15:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[COSTCALCULATIONUPDATE]
ON [dbo].[TBLMOVEMENT]
AFTER UPDATE
AS
BEGIN
	UPDATE TBLMOVEMENT
		SET COST = 0
		FROM DELETED
		WHERE TBLMOVEMENT.MOVEMENTID = DELETED.MOVEMENTID;
	UPDATE TBLMOVEMENT
		SET COST = INSERTED.QUANTITY * TBLPRODUCTS.PRODUCTPRICE
		FROM INSERTED
		INNER JOIN TBLPRODUCTS
		ON TBLPRODUCTS.PRODUCTID = INSERTED.PRODUCT
		WHERE TBLMOVEMENT.MOVEMENTID = INSERTED.MOVEMENTID;
	
END;
GO

ALTER TABLE [dbo].[TBLMOVEMENT] ENABLE TRIGGER [COSTCALCULATIONUPDATE]
GO


